#!/bin/bash

if test -f "$HOME/.secrets"; then
    source $HOME/.secrets
fi

MAILCOUNTER=`curl -u $EMAIL_USERNAME:$EMAIL_PASSWORD --silent "https://mail.google.com/mail/feed/atom" \ | xmllint --format - \ | sed -n 's#<fullcount>\(.*\)</fullcount>#\1#p'`
echo $MAILCOUNTER
