#!/usr/bin/env bash
        
IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | tail -1)
echo $IP;

# Do not run these when home
if [[ $IP != "192.168.68"* ]]; then
    firefox &
    mailspring &
    discord &
    ferdium &
else
#	synergyc --name Work 192.168.68.106
    waynergy &
fi

#nvidia-offload firefox &
#mailspring --use-gl=desktop &
#discord --use-gl=desktop &
#ferdium --use-gl=desktop &
#waynergy --name Work -c 192.168.68.106


gitkraken &
code &