#! /bin/bash

# Fix for autorandr profile switching at boot
autorandr -c $(autorandr | grep "(detected)" | sed "s/ (detected)//")

# Nvidia
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

picom --experimental-backends & # Compositor
~/.config/polybar/launch.sh & # Status bar
xsetroot -cursor_name left_ptr & # X cursor fix
dunst & # Notifications
feh --bg-fill ~/Pictures/Wallpapers/wallpaper.jpg & # Wallpaper
sxhkd & # Keyboard shortcuts
xss-lock -- betterlockscreen -l dim & # Lockscreen handler

# java fix?
wmname LG3D

source ./variables

./workspaces &

#borders 
bspc config border_width         3
bspc config normal_border_color	 '#444545'
bspc config focused_border_color '#C70039'

bspc config window_gap           16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# bspc config single_monocle	 true

bspc rule -a Google-chrome desktop=$chrome
bspc rule -a Code desktop=$code
bspc rule -a Ferdi desktop=$chat
bspc rule -a discord desktop=$chat
bspc rule -a Mailspring desktop=$mail
bspc rule -a Spotify desktop=$spotify

startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file
  ~/.config/autostart.sh &
fi
