#! /bin/bash

# Fix for autorandr profile switching at boot
#autorandr -c $(autorandr | grep "(detected)" | sed "s/ (detected)//")

# Nvidia
#xrandr --setprovideroutputsource modesetting NVIDIA-0
#xrandr --auto

~/.screenlayout/screenlayout.sh

picom & # Compositor
~/.config/polybar/launch.sh & # Status bar
xsetroot -cursor_name left_ptr & # X cursor fix
dunst & # Notifications
feh --bg-fill ~/Pictures/Wallpapers/wallpaper.jpg & # Wallpaper
sxhkd & # Keyboard shortcuts
xss-lock -- betterlockscreen -l dim & # Lockscreen handler

# java fix?
#wmname LG3D

source ~/.config/bspwm/variables

#~/.screenlayout/screenlayout.sh
~/.config/bspwm/workspaces

#borders 
bspc config border_width         0
#bspc config normal_border_color	 '#4A4A4A'
#bspc config focused_border_color '#676767'

bspc config window_gap           16

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# bspc config single_monocle	 true

bspc rule -a Google-chrome desktop=$chrome
bspc rule -a Code desktop=$code
bspc rule -a Ferdi desktop=$chat
bspc rule -a gitkraken desktop=$git
bspc rule -a discord desktop=$chat
bspc rule -a Mailspring desktop=$mail
bspc rule -a Spotify desktop=$spotify
bspc rule -a QuickSynergy desktop=$other3

startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file
  ~/.config/autostart.sh &
fi
