#! /bin/bash

bspc subscribe monitor | while read -r line; do
        case $line in
                        monitor_add*|monitor_remove*)
                                        echo $line && killall bspc && sleep 1 && bspc wm -r
        esac
done
